image: fedora/latest
packages:
  - dotnet
  - dotnet-sdk-5.0
  - wget
  - unzip
  - zip
tasks:
  - download-dalamud: |
      mkdir dalamud
      cd dalamud
      wget https://github.com/goatcorp/dalamud-distrib/raw/main/latest.zip
      unzip latest.zip
      rm latest.zip
  - build-plugin: |
      cd TheHeartOfTheParty/TheHeartOfTheParty
      dotnet build -c Release -p:IsCI=true
  - package: |
      cd TheHeartOfTheParty/TheHeartOfTheParty/bin/Release/net5-windows
      zip -r release.zip TheHeartOfTheParty
artifacts:
  - TheHeartOfTheParty/TheHeartOfTheParty/bin/Release/net5-windows/TheHeartOfTheParty/latest.zip
  - TheHeartOfTheParty/TheHeartOfTheParty/bin/Release/net5-windows/release.zip
